#app.yaml
#this contains the meta-data for the app and tells Google App Engine how to run it.


application: sample-webstore #replace this with your own application id#
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: app.application
